# === application.yaml ===
server:
  port: 8084

spring:
  application:
    name: SERVICIO-NOTIFICACIONES
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL}"
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/db_notificaciones}
    username: ${DB_USERNAME:rapidouser}
    password: ${DB_PASSWORD:rapidopass}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}

# ── Configuración de Eureka ──
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
  instance:
    hostname: servicio-notificaciones
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: true

# ── Endpoints de Actuator ──
management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh

logging:
  level:
    # CORRECCIÓN: Paquete base corregido para asegurar que los logs se impriman
    com.rapidocourier: DEBUG