server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  instance:
    # Fuerza el uso del nombre del contenedor para la red interna
    hostname: eureka-server
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      # Referencia explícita al nombre del host del contenedor
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000

management:
  endpoints:
    web:
      exposure:
        include: health,info